[[zl]]
== Long Instruction Extensions


RV32I and RV64I and all instructions based on them are encoded in the standard
32-bit instruction format. The RISC-V Long Instruction extension provides a new
instruction format that allows for 48-bit and 64-bit instructions. The extension
is designed to allow for future expansion of the RISC-V instruction set, while
maintaining compatibility with existing software and hardware.

=== Long Instruction Encoding

The instruction coding extends the ratified 32-bit and compressed 16-bit instruction format and requires ILEN=16. Each instruction is encoded in 16 bit parcels.

include::images/bytefield/zl-encoding-scheme.edn[]

The long instruction format adds new opcode spaces for each of the extended lengths. For 48-bit instructions, the opcode space of a total of 12 opcodesis defined by:

 - Bit 5 and 6 of the first parcel can be arbitrary values. This part of the opcode should be used to indicate information on the type of instruction to support pipelines that did not fetch the full word. For example control flow instructions should be easy to identify.
 - Bit 0 and 1 of the third parcel can be all values except 11.

[NOTE]
====
Out of the 12 opcodes, 2 should be reserved for custom instructions. An assignment of the opcoce space is tbd.
====

=== Base Instruction Formats

Additional instruction formats are defined for 48-bit instructions:

include::images/wavedrom/zl-formats.edn[]

[NOTE]
====
Those are basically just the extensions of the existing formats. Based on the included instructions and as a reference for future optional extensions, more formats will be defined.
====

=== Immediate Encoding Variants

The immediate encoding variants are defined for the base instruction formats. It maps the immediate values from the instruction formats to the immediate values used in the instruction semantics (sign extension).

==== RV32I Immediate Encoding Variants

include::images/wavedrom/zl-immediates32.edn[]

==== RV64I Immediate Encoding Variants

include::images/wavedrom/zl-immediates64.edn[]

=== Instructions

==== Integer Register-Immediate Instructions

include::images/wavedrom/zl-li.edn[]
[[zl-li]]

==== Unconditional Jumps

include::images/wavedrom/zl-jal.edn[]
[[zl-jal]]

include::images/wavedrom/zl-jalr.edn[]
[[zl-jalr]]

==== Conditional Branches

include::images/wavedrom/zl-branches.edn[]
[[zl-branches]]

==== Load and Store Instructions

include::images/wavedrom/zl-load-store.edn[]
[[zl-load-store]]
